### ISSUE TITLE
Alignment Subfolders are Empty

### ISSUE THREAD

**Issue by dylan-k** [uwidev/life-disciplines-projects#4]
I expected to find example notes in the folders daily, weekly, and so on. Are they missing? What would you suggest to include in the various notes for these?

**Comment by uwidev** [comment]
They were not included since there isn't a one-size-fit-all solution for doing alignment on a daily, weekly, monthly-basis. I would recommend checking out the included `Ceremonies (Scrum)` note as a guide to creating your own alignment.

I may look to include an extremely generic example of alignments, and may redirect people to the note stated above. I'm running out of things to add and polish onto this project.
